# Auto-generated: imports all payload option definitions
{ lib, ... }:

{
  imports = [
    ./apple/Configuration.nix
    ./apple/com-apple-ADCertificate-managed.nix
    ./apple/com-apple-AIM-account.nix
    ./apple/com-apple-AssetCache-managed.nix
    ./apple/com-apple-Dictionary.nix
    ./apple/com-apple-DirectoryService-managed.nix
    ./apple/com-apple-DiscRecording.nix
    ./apple/com-apple-GlobalPreferences.nix
    ./apple/com-apple-MCX-EnergySaver.nix
    ./apple/com-apple-MCX-FileVault2.nix
    ./apple/com-apple-MCX-FileVaultOptions.nix
    ./apple/com-apple-MCX-GuestAccount.nix
    ./apple/com-apple-MCX-MobileAccounts.nix
    ./apple/com-apple-MCX-TimeMachine.nix
    ./apple/com-apple-MCX-TimeServer.nix
    ./apple/com-apple-MCX-WiFiManagedSettings.nix
    ./apple/com-apple-NSExtension.nix
    ./apple/com-apple-SetupAssistant-managed.nix
    ./apple/com-apple-ShareKitHelper.nix
    ./apple/com-apple-SoftwareUpdate.nix
    ./apple/com-apple-SubmitDiagInfo.nix
    ./apple/com-apple-SystemConfiguration.nix
    ./apple/com-apple-TCC-configuration-profile-policy.nix
    ./apple/com-apple-airplay-security.nix
    ./apple/com-apple-airplay.nix
    ./apple/com-apple-airprint.nix
    ./apple/com-apple-app-lock.nix
    ./apple/com-apple-applicationaccess-iOS.nix
    ./apple/com-apple-applicationaccess-macOS.nix
    ./apple/com-apple-applicationaccess-new.nix
    ./apple/com-apple-applicationaccess-tvOS.nix
    ./apple/com-apple-appstore.nix
    ./apple/com-apple-asam.nix
    ./apple/com-apple-associated-domains.nix
    ./apple/com-apple-caldav-account.nix
    ./apple/com-apple-carddav-account.nix
    ./apple/com-apple-cellular.nix
    ./apple/com-apple-cellularprivatenetwork-managed.nix
    ./apple/com-apple-conferenceroomdisplay.nix
    ./apple/com-apple-configurationprofile-identification.nix
    ./apple/com-apple-dashboard.nix
    ./apple/com-apple-declarations.nix
    ./apple/com-apple-desktop.nix
    ./apple/com-apple-dnsProxy-managed.nix
    ./apple/com-apple-dnsSettings-managed.nix
    ./apple/com-apple-dock.nix
    ./apple/com-apple-domains.nix
    ./apple/com-apple-eas-account.nix
    ./apple/com-apple-education.nix
    ./apple/com-apple-ews-account.nix
    ./apple/com-apple-extensiblesso.nix
    ./apple/com-apple-familycontrols-contentfilter.nix
    ./apple/com-apple-familycontrols-timelimits-v2.nix
    ./apple/com-apple-fileproviderd.nix
    ./apple/com-apple-finder.nix
    ./apple/com-apple-firstactiveethernet-managed.nix
    ./apple/com-apple-firstethernet-managed.nix
    ./apple/com-apple-font.nix
    ./apple/com-apple-gamed.nix
    ./apple/com-apple-globalethernet-managed.nix
    ./apple/com-apple-google-oauth.nix
    ./apple/com-apple-ironwood-support.nix
    ./apple/com-apple-jabber-account.nix
    ./apple/com-apple-ldap-account.nix
    ./apple/com-apple-loginitems-managed.nix
    ./apple/com-apple-loginwindow.nix
    ./apple/com-apple-lom.nix
    ./apple/com-apple-mail-managed.nix
    ./apple/com-apple-mcxloginscripts.nix
    ./apple/com-apple-mcxprinting.nix
    ./apple/com-apple-mdm.nix
    ./apple/com-apple-mobiledevice-passwordpolicy.nix
    ./apple/com-apple-networkusagerules.nix
    ./apple/com-apple-notificationsettings-iOS.nix
    ./apple/com-apple-notificationsettings-macOS.nix
    ./apple/com-apple-osxserver-account.nix
    ./apple/com-apple-preference-security.nix
    ./apple/com-apple-profileRemovalPassword.nix
    ./apple/com-apple-proxy-http-global.nix
    ./apple/com-apple-relay-managed.nix
    ./apple/com-apple-screensaver-user.nix
    ./apple/com-apple-screensaver.nix
    ./apple/com-apple-secondactiveethernet-managed.nix
    ./apple/com-apple-secondethernet-managed.nix
    ./apple/com-apple-security-FDERecoveryKeyEscrow.nix
    ./apple/com-apple-security-FDERecoveryRedirect.nix
    ./apple/com-apple-security-acme.nix
    ./apple/com-apple-security-certificatepreference.nix
    ./apple/com-apple-security-certificatetransparency.nix
    ./apple/com-apple-security-firewall.nix
    ./apple/com-apple-security-pem.nix
    ./apple/com-apple-security-pkcs1.nix
    ./apple/com-apple-security-pkcs12.nix
    ./apple/com-apple-security-root.nix
    ./apple/com-apple-security-scep.nix
    ./apple/com-apple-security-smartcard.nix
    ./apple/com-apple-servicemanagement.nix
    ./apple/com-apple-shareddeviceconfiguration.nix
    ./apple/com-apple-sso.nix
    ./apple/com-apple-subscribedcalendar-account.nix
    ./apple/com-apple-syspolicy-kernel-extension-policy.nix
    ./apple/com-apple-system-extension-policy.nix
    ./apple/com-apple-system-logging.nix
    ./apple/com-apple-systemmigration.nix
    ./apple/com-apple-systempolicy-control.nix
    ./apple/com-apple-systempolicy-managed.nix
    ./apple/com-apple-systempreferences.nix
    ./apple/com-apple-systemuiserver.nix
    ./apple/com-apple-thirdactiveethernet-managed.nix
    ./apple/com-apple-thirdethernet-managed.nix
    ./apple/com-apple-tvremote.nix
    ./apple/com-apple-universalaccess.nix
    ./apple/com-apple-webClip-managed.nix
    ./apple/com-apple-webcontent-filter.nix
    ./apple/com-apple-wifi-managed.nix
    ./apple/com-apple-xsan-preferences.nix
    ./apple/com-apple-xsan.nix
    ./apple/loginwindow.nix
    ./managed-apple/com-apple-AdLib.nix
    ./managed-apple/com-apple-NetworkBrowser.nix
    ./managed-apple/com-apple-Safari-SandboxBroker.nix
    ./managed-apple/com-apple-Siri.nix
    ./managed-apple/com-apple-Spotlight.nix
    ./managed-apple/com-apple-TimeMachine.nix
    ./managed-apple/com-apple-assistant-support.nix
    ./managed-apple/com-apple-controlcenter.nix
    ./managed-apple/com-apple-coreservices-uiagent.nix
    ./managed-apple/com-apple-desktopservices.nix
    ./managed-apple/com-apple-dt-Xcode.nix
    ./managed-apple/com-apple-finder.nix
    ./managed-apple/com-apple-freeform.nix
    ./managed-apple/com-apple-iBooksX.nix
    ./managed-apple/com-apple-iTunes.nix
    ./managed-apple/com-apple-iWork-Keynote.nix
    ./managed-apple/com-apple-iWork-Numbers.nix
    ./managed-apple/com-apple-iWork-Pages.nix
    ./managed-apple/com-apple-icloud-managed.nix
    ./managed-apple/com-apple-mDNSResponder.nix
    ./managed-apple/com-apple-preferences-sharing-SharingPrefsExtension.nix
    ./managed-apple/com-apple-print-add.nix
    ./managed-apple/com-apple-python.nix
    ./managed-apple/com-apple-safari.nix
    ./managed-apple/com-apple-screencapture.nix
    ./managed-apple/com-apple-security.nix
    ./managed-apple/com-apple-sharingd.nix
    ./managed-apple/com-apple-systemuiserver.nix
    ./managed-apple/com-apple-timed.nix
    ./managed-apple/com-apple-touristd.nix
    ./managed-applications/ManagedInstalls.nix
    ./managed-applications/MunkiReport.nix
    ./managed-applications/SupportCompanion.nix
    ./managed-applications/com-1password-1password.nix
    ./managed-applications/com-ThomsonResearchSoft-EndNote.nix
    ./managed-applications/com-agilebits-onepassword7.nix
    ./managed-applications/com-alectrona-patch-agent.nix
    ./managed-applications/com-alectrona-patch-notifier.nix
    ./managed-applications/com-alectrona-patch.nix
    ./managed-applications/com-anthropic-claudefordesktop.nix
    ./managed-applications/com-apple-Compressor.nix
    ./managed-applications/com-apple-Enterprise-Connect.nix
    ./managed-applications/com-apple-FinalCut.nix
    ./managed-applications/com-apple-TextEdit.nix
    ./managed-applications/com-apple-garageband10.nix
    ./managed-applications/com-apple-iMovieApp.nix
    ./managed-applications/com-apple-logic10.nix
    ./managed-applications/com-apple-motionapp.nix
    ./managed-applications/com-barebones-bbedit.nix
    ./managed-applications/com-brave-Browser.nix
    ./managed-applications/com-citrix-receiver-nomas.nix
    ./managed-applications/com-cloudflare-warp.nix
    ./managed-applications/com-crowdstrike-falcon.nix
    ./managed-applications/com-dare-zappl-preferences.nix
    ./managed-applications/com-docker-config.nix
    ./managed-applications/com-electron-dialpad.nix
    ./managed-applications/com-frontapp-Front.nix
    ./managed-applications/com-fxfactory-FxFactory.nix
    ./managed-applications/com-gilburns-patcher.nix
    ./managed-applications/com-gingerlabs-notability-iOS.nix
    ./managed-applications/com-gingerlabs-notability-macOS.nix
    ./managed-applications/com-github-ants-framework.nix
    ./managed-applications/com-github-macadmins-Nudge.nix
    ./managed-applications/com-github-macadmins-SupportCompanion.nix
    ./managed-applications/com-github-mpanighetti-install-or-defer.nix
    ./managed-applications/com-github-salopensource-sal.nix
    ./managed-applications/com-github-wavebirddash-install-or-defer.nix
    ./managed-applications/com-google-Chrome.nix
    ./managed-applications/com-google-Keystone.nix
    ./managed-applications/com-google-drivefs-settings.nix
    ./managed-applications/com-google-santa.nix
    ./managed-applications/com-grahamgilbert-crypt.nix
    ./managed-applications/com-grammarly-ProjectLlama.nix
    ./managed-applications/com-granola-app.nix
    ./managed-applications/com-hjuutilainen-MunkiAdmin.nix
    ./managed-applications/com-hjuutilainen-bigsurblocker.nix
    ./managed-applications/com-jamf-connect-login-Okta.nix
    ./managed-applications/com-jamf-connect-login-OpenID.nix
    ./managed-applications/com-jamf-connect-shares.nix
    ./managed-applications/com-jamf-connect-sync.nix
    ./managed-applications/com-jamf-connect-verify.nix
    ./managed-applications/com-jamf-setupmanager.nix
    ./managed-applications/com-jamf-trust.nix
    ./managed-applications/com-jelockwood-pinpoint.nix
    ./managed-applications/com-jigsaw24-Elevate24.nix
    ./managed-applications/com-jigsaw24-ElevateSecurityLogs.nix
    ./managed-applications/com-keepersecurity-passwordmanager.nix
    ./managed-applications/com-macjutsu-super.nix
    ./managed-applications/com-macpaw-site-theunarchiver.nix
    ./managed-applications/com-mcneel-rhinoceros.nix
    ./managed-applications/com-microsoft-Edge.nix
    ./managed-applications/com-microsoft-Excel.nix
    ./managed-applications/com-microsoft-Office365ServiceV2.nix
    ./managed-applications/com-microsoft-OneDrive.nix
    ./managed-applications/com-microsoft-OneDriveUpdater.nix
    ./managed-applications/com-microsoft-Outlook.nix
    ./managed-applications/com-microsoft-Powerpoint.nix
    ./managed-applications/com-microsoft-SkypeForBusiness.nix
    ./managed-applications/com-microsoft-VSCode.nix
    ./managed-applications/com-microsoft-Word.nix
    ./managed-applications/com-microsoft-autoupdate-fba.nix
    ./managed-applications/com-microsoft-autoupdate2.nix
    ./managed-applications/com-microsoft-errorreporting.nix
    ./managed-applications/com-microsoft-office.nix
    ./managed-applications/com-microsoft-onenote-mac.nix
    ./managed-applications/com-microsoft-rdc-macos.nix
    ./managed-applications/com-microsoft-wdav.nix
    ./managed-applications/com-missiveapp-osx.nix
    ./managed-applications/com-northpolesec-santa.nix
    ./managed-applications/com-okta-mobile-auth-service-extension.nix
    ./managed-applications/com-okta-mobile.nix
    ./managed-applications/com-openai-codex.nix
    ./managed-applications/com-papercut-printdeploy-client.nix
    ./managed-applications/com-parallels-desktop-managedprefs.nix
    ./managed-applications/com-pratikkumar-airserver-mac.nix
    ./managed-applications/com-secondsonconsulting-baseline.nix
    ./managed-applications/com-secondsonconsulting-renew.nix
    ./managed-applications/com-sentinelone-registration-token.nix
    ./managed-applications/com-skype-skype.nix
    ./managed-applications/com-sqwarq-DetectX-Swift.nix
    ./managed-applications/com-tinyspeck-slackmacgap.nix
    ./managed-applications/com-todesktop-230313mzl4w4u92.nix
    ./managed-applications/com-trelica-macapp.nix
    ./managed-applications/com-trusourcelabs-NoMAD.nix
    ./managed-applications/com-twingate-macos.nix
    ./managed-applications/com-twocanoes-xcreds.nix
    ./managed-applications/com-unity3d-UnityEditor5-x.nix
    ./managed-applications/com-vpntracker-365mac-config.nix
    ./managed-applications/com-zappl-AppBar.nix
    ./managed-applications/com-zscaler-installparams.nix
    ./managed-applications/corp-sap-privileges.nix
    ./managed-applications/cx-c3-theunarchiver.nix
    ./managed-applications/de-fau-rrze-NetworkShareMounter.nix
    ./managed-applications/dev-firezone-firezone.nix
    ./managed-applications/edu-ncsu-confboard.nix
    ./managed-applications/edu-psu-macoslaps.nix
    ./managed-applications/fr-handbrake-HandBrake.nix
    ./managed-applications/io-macadmins-Outset.nix
    ./managed-applications/io-tailscale-ipn-macos.nix
    ./managed-applications/io-tailscale-ipn-macsys.nix
    ./managed-applications/menu-nomad-NoMADPro.nix
    ./managed-applications/menu-nomad-login-ad.nix
    ./managed-applications/menu-nomad-login-okta.nix
    ./managed-applications/menu-nomad-shares.nix
    ./managed-applications/net-glencode-Particulars-Widget.nix
    ./managed-applications/net-glencode-Particulars.nix
    ./managed-applications/net-whatsapp-WhatsApp.nix
    ./managed-applications/nl-root3-support.nix
    ./managed-applications/notion-id.nix
    ./managed-applications/org-churchofjesuschrist-dorm.nix
    ./managed-applications/org-mozilla-firefox.nix
    ./managed-applications/org-sveinbjorn-Platypus.nix
    ./managed-applications/org-videolan-vlc.nix
    ./managed-applications/uk-co-dataJAR-jamJAR.nix
    ./managed-applications/us-zoom-config.nix
    ./managed-applications/xyz-techitout-appAutoPatch.nix
    ./managed-developer/com-profilecreator-developer-deprecated.nix
    ./managed-developer/com-profilecreator-developer-exclude.nix
    ./managed-developer/com-profilecreator-developer-note.nix
    ./managed-developer/com-profilecreator-developer-popupbutton.nix
    ./managed-developer/com-profilecreator-developer-require.nix
    ./managed-developer/com-profilecreator-developer-slider.nix
    ./managed-developer/com-profilecreator-developer-substitution_variables.nix
    ./managed-developer/com-profilecreator-developer-tableview.nix
    ./managed-developer/com-profilecreator-developer-textfield.nix
    ./managed-developer/com-profilecreator-developer-textfieldfloat.nix
    ./managed-developer/com-profilecreator-developer-textfieldinteger.nix
  ];
}